Feat/dockerize frontend
idodav/sharkio pull request #127
Opened 2023-07-19 13:05 UTC by Oferlis

2023-07-20 15:23 UTC, idodav requested changes

2023-07-20 15:23 UTC, idodav commented on docker-compose.yml
Please remove the file

2023-07-20 15:23 UTC, idodav commented on traffic-dashboard/Dockerfile
Please don't assume that the dist app exists.
Copy the entire source the dockerfile. Build the projects inside the dockerfile.
Create a multistage dockerfile. First is the builder. And the second is the final image. Copy the assets from the builder to the final base image.

2023-07-21 09:22 UTC, idodav submitted a review, later dismissed

2023-07-23 08:09 UTC, SID262000 reviewed
@Oferlis Please add documentation around your changes. It's extremely important to have a well documented codebase that would eventually help to onboard new developers with ease.
Also, can you please confirm in case these changes have been run through any linters, Thanks 
cc: @idodav

2023-07-23 08:10 UTC, idodav commented
@SID262000 How do you suggest that we document such change?

2023-07-23 08:24 UTC, SID262000 commented
@idodav Please refer to this section. This will really help to improve the quality of docker files(both existing & new ones).

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

cc: @Oferlis

2023-07-24 10:25 UTC, idodav commented
@Oferlis Is this ready for review?

2023-07-24 11:00 UTC, Oferlis commented
@idodav Please take a look at the changes, and proxying works, but ports must be exposed.
A solution is exposing a range of ports and notifying users that these ports must be available for use by Sharkio.
What do you think? is there a better solution?
I could also open this issue to discussion in the Discord channel

2023-07-24 11:28 UTC, idodav commented
> 

It's fine. The EXPOSE keyword is mainly for documentation.
It doesn't actually expose the ports.

2023-07-25 05:10 UTC, idodav commented on docker-compose.yml
> +    ports:
You could expose 5550-5560 for now.
we will figure out a different splution later.

2023-07-25 07:11 UTC, Oferlis commented on docker-compose.yml
> +    ports:
Done, PR is ready for review

2023-07-25 07:40 UTC, merged