82 docs add swaggerdocs to traffic sniffer controllers
idodav/sharkio pull request #94
Opened 2023-07-08 19:59 UTC by idodav

- feat: swagger jsdoc documentation
- feat: swagger jsdoc

2023-07-08 20:13 UTC, idodav commented
Swagger can be accessed through http://localhost:5012/api-docs


<img width="1511" alt="Screenshot 2023-07-08 at 22 59 55" src="https://github.com/idodav/sharkio/assets/21335259/a3f734b1-0221-4c83-8283-96d63ae26527">
<img width="1511" alt="Screenshot 2023-07-08 at 23 00 08" src="https://github.com/idodav/sharkio/assets/21335259/864ef67b-2cc4-493f-bee6-a206122ea0b2">

2023-07-09 14:49 UTC, nkotzrenko requested changes
Some missing data

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/mock-manager-controller.ts
> +     *              type: object
Is the request body mandatory in this doc? I mean - all the function body references is the params object

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/mock-manager-controller.ts
> +     *              type: object
Is it relevant?

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/mock-manager-controller.ts
> +     *              type: object
Is it relevant?

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/mock-manager-controller.ts
> +     *              type: object
Missing mockId property

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/mock-manager-controller.ts
> +     *              type: object
What is the structure of the body?

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/mock-manager-controller.ts
> +     *              type: object
In the body, mockId is missing

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/sniffer-manager-controller.ts
> +     */
Missing reference to parameters object

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/sniffer-manager-controller.ts
> +     *              type: object
What is the structure of the body?

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/sniffer-manager-controller.ts
> +     */
Structure body is missing

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/sniffer-manager-controller.ts
> +     *              type: object
Add the structure of the body

2023-07-09 14:49 UTC, nkotzrenko commented on traffic-sniffer/lib/sniffer-manager/sniffer-manager-controller.ts
> +     *     responses:
Add structure to body

2023-07-09 14:50 UTC, nkotzrenko approved these changes

2023-07-09 14:50 UTC, nkotzrenko commented
I approved these changes after speaking to @idodav - we can fix it later (as part of the zod validations PR) on my end

2023-07-09 14:52 UTC, merged